# Generated by Django 5.0.4 on 2024-06-14 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity-In-Stock'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.CharField(default='Kings Suppliers', max_length=50, verbose_name='Supplier Name'),
        ),
    ]
