# Generated by Django 5.0.4 on 2024-06-14 21:17

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_order_quantity_order_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Supplier Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email address')),
                ('product', models.CharField(max_length=1000, verbose_name='Goods to Supply')),
                ('deliverytime', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Delivery Timeframe(In days)')),
                ('accepted_payment', models.CharField(max_length=50, verbose_name='Payment method accepted')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
            ],
        ),
    ]
